### ISSUE TITLE
Homepage background

### ISSUE THREAD

**Issue by Fnyasimi** [bioinformatics-hub-ke/BOSS22#1]
What would be the best homepage background?

**Comment by Fnyasimi** [comment]
@kipkurui I did a banner shared on slack. I will try get an svg version of it.

@bkmgit which of the two will blend well with the website theme?

**Comment by bkmgit** [comment]
https://github.com/bioinformatics-hub-ke/BOSS22/pull/49
https://github.com/bioinformatics-hub-ke/BOSS22/pull/61
