### ISSUE TITLE
Contact email on site

### ISSUE THREAD

**Issue by bkmgit** [bioinformatics-hub-ke/BOSS22#25]
Add contact email to website

**Comment by Fnyasimi** [comment]
Would be nice to plug our social media on the footer (right side which is empty) using avatars @bkmgit 
[Youtube](https://www.youtube.com/channel/UCWvCsVW7BF3Nml5VpLOdU5g)
[LinkedIn](https://www.linkedin.com/company/bioinformatics-hub-of-kenya-initiative-bhki)
[Twitter](https://twitter.com/bioinfohub_ke)
