### ISSUE TITLE
Website colors

### ISSUE THREAD

**Issue by karegapauline** [bioinformatics-hub-ke/BOSS22#44]
@bkmgit see this [link](https://visme.co/blog/website-color-schemes/), 27. Gorgeous contrast. I think those colors work.

**Comment by bkmgit** [comment]
@karegapauline There are a lot of choices. Assuming only the colors need to be changed please indicate the color changes that should be made to the dark and light themes. Ideally take a screen shot and put a label on each color that should be changed, or have a list in this thread. It may be helpful to also check
- https://www.toptal.com/designers/colorfilter 
- http://a11yrocks.com/colorPalette/
- https://palette.rocks/
- http://colorsafe.co/

**Comment by karegapauline** [comment]
This is a helpful site. http://a11yrocks.com/colorPalette/
#AAC789 option is my suggestion.

**Comment by bkmgit** [comment]
Please be specific. There are at least 5 colors for each skin.
- Dark 
  - Green BOSSCon logo
  - Site background color
  - Light text
  - Dark pink menu highlight
  - Light pink menu highlight
  - Dark footer
- Light
 - Green BOSSCon logo
 - Site background color
 - Dark text
 - Dark pink menu highlight
 - Light pink menu highlight
 - Dark footer

**Comment by karegapauline** [comment]
The contrast in #AAC789, with the dark and light green. exactly as it is is I was suggesting, with a small change at the footer. I don't know if this breakdown helps. 

Dark
Green BOSSCon logo
Site background-color
Light text
Dark green menu highlight (#AAC789)
Light green menu highlight 
Grey (#808080) footer

Light
Green BOSSCon logo
Site background-color
Dark text
Dark green menu highlight
Light green menu highlight
Grey footer

**Comment by bkmgit** [comment]
@karegapauline Thanks. HTML color code for light green? Currently the logo BOSSCon 22 uses #55ba3f - it probably it should use #AAC789 or whatever color code is used for light green.

**Comment by bkmgit** [comment]
Maybe #437356 works for light green, or can continue with pink for the menu highlight, for example #F34A53

**Comment by karegapauline** [comment]
#437356 this works, I was thinking it can replace the pink menu highlight.

**Comment by bkmgit** [comment]
![Dark](https://user-images.githubusercontent.com/1679477/158398536-0214e995-6252-431e-88c4-5dd2fd28d0c1.png)
![Light](https://user-images.githubusercontent.com/1679477/158398570-3cbeece1-7111-4f28-83b6-e9254400431f.png)
Sample screen shots from https://github.com/bioinformatics-hub-ke/BOSS22/pull/48

**Comment by bkmgit** [comment]
![Footer](https://user-images.githubusercontent.com/1679477/158399554-83ace089-bb08-40c6-b0d4-088df1a50d60.png)
Footer

**Comment by bkmgit** [comment]
Please merge if ok. The template has a formula to calculate the lighter menu highlight color, at present this is unchanged.

**Comment by bkmgit** [comment]
It gives a light green color.

**Comment by bkmgit** [comment]
https://github.com/bioinformatics-hub-ke/BOSS22/pull/48
