### ISSUE TITLE
Rendering on hand held devices

### ISSUE THREAD

**Issue by Fnyasimi** [bioinformatics-hub-ke/BOSS22#47]
The top navigation bar is slightly off

**Comment by bkmgit** [comment]
Can you add more detail on what should be changed?

**Comment by bkmgit** [comment]
Previewed the site at https://ready.mobi/ - https://github.com/bioinformatics-hub-ke/BOSS22/pull/48 possibly will resolve this as it removes "BOSS 2022" from the header.

**Comment by bkmgit** [comment]
Other related tools:
- https://mobilemoxie.com/tools/mobile-page-test/
- https://www.responsinator.com
- https://search.google.com/test/mobile-friendly
- https://www.bing.com/webmaster/tools/mobile-friendliness

**Comment by Fnyasimi** [comment]
Checked it out on those platforms and the top navigation bars are still tucked behind each other i.e you cannot access the registration tab

**Comment by bkmgit** [comment]
Ok hamburger menu feature described at https://mmistakes.github.io/minimal-mistakes/docs/navigation/#masthead seems not to be working.

**Comment by bkmgit** [comment]
Related links
- https://github.com/mmistakes/minimal-mistakes/pull/2674
- https://github.com/mmistakes/minimal-mistakes/issues/1301

**Comment by bkmgit** [comment]
@Fnyasimi Thanks for reporting this. Closing due to https://github.com/bioinformatics-hub-ke/BOSS22/pull/63. Feel free to reopen if you find the issue is not resolved.
